name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # https://github.com/Azure/setup-helm
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.2

      # https://github.com/actions/setup-python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true

      # https://github.com/helm/chart-testing-action
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          #!/bin/sh
          set -eux
          changed=$(ct list-changed --target-branch "main")
          if [ -n "$changed" ]; then
            echo "changed=true" | tee -a "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --target-branch "main"

      # https://github.com/helm/kind-action
      - name: Set up a Kubernetes-in-Docker cluster
        uses: helm/kind-action@v1.5.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install
